"""Deterministic PDF export of an Annex IV dossier (reportlab).

reportlab is pure-Python (no native deps — identical on Windows and Linux CI) and
supports an ``invariant`` mode that fixes timestamps and the document id, so the
same dossier renders to byte-identical PDF. The load-bearing determinism is the
dossier MODEL (pinned by the golden); the PDF is a deterministic rendering of it.
"""

import io

from reportlab import rl_config
from reportlab.lib import colors
from reportlab.lib.enums import TA_LEFT
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import mm
from reportlab.platypus import Paragraph, SimpleDocTemplate, Spacer, Table, TableStyle

from attestor.annexiv.model import AnnexIVDossier, DossierSection


def render_pdf(dossier: AnnexIVDossier) -> bytes:
    """Render ``dossier`` to a deterministic PDF and return the bytes."""
    previous = rl_config.invariant
    rl_config.invariant = 1
    try:
        return _build(dossier)
    finally:
        rl_config.invariant = previous


def _build(dossier: AnnexIVDossier) -> bytes:
    buffer = io.BytesIO()
    doc = SimpleDocTemplate(
        buffer,
        pagesize=A4,
        title="Annex IV Technical Documentation",
        author="Attestor",
        leftMargin=20 * mm,
        rightMargin=20 * mm,
        topMargin=18 * mm,
        bottomMargin=18 * mm,
    )
    styles = getSampleStyleSheet()
    body = styles["BodyText"]
    guidance_style = ParagraphStyle(
        "Guidance", parent=body, textColor=colors.HexColor("#555555"), alignment=TA_LEFT
    )

    flow: list = [
        Paragraph("Annex IV — Technical Documentation", styles["Title"]),
        Paragraph("Traceable scaffold generated by Attestor (not legal advice).", guidance_style),
        Spacer(1, 6 * mm),
        _metadata_table(dossier),
        Spacer(1, 4 * mm),
    ]

    if dossier.provisional_note:
        flow.append(Paragraph(f"<b>Provisional:</b> {dossier.provisional_note}", guidance_style))
        flow.append(Spacer(1, 4 * mm))

    if dossier.legal_basis is not None:
        lb = dossier.legal_basis
        flow.append(
            Paragraph(
                f"<b>Legal basis:</b> {lb.reference} — {lb.title} "
                f"(effective {lb.effective_date.isoformat()})",
                body,
            )
        )
        flow.append(Spacer(1, 4 * mm))

    for section in dossier.sections:
        flow.extend(_section_flowables(section, styles, guidance_style))

    doc.build(flow)
    return buffer.getvalue()


def _metadata_table(dossier: AnnexIVDossier) -> Table:
    rows = [
        ["System", dossier.system_name],
        ["Risk", dossier.risk.value],
        ["Scenario", dossier.scenario],
        ["Bundle", f"{dossier.bundle_version} ({dossier.bundle_sha256[:16]}…)"],
        ["Classification checksum", f"{dossier.classification_checksum[:16]}…"],
    ]
    table = Table(rows, colWidths=[55 * mm, 110 * mm])
    table.setStyle(
        TableStyle(
            [
                ("FONTNAME", (0, 0), (0, -1), "Helvetica-Bold"),
                ("FONTSIZE", (0, 0), (-1, -1), 9),
                ("GRID", (0, 0), (-1, -1), 0.4, colors.HexColor("#cccccc")),
                ("VALIGN", (0, 0), (-1, -1), "TOP"),
                ("ROWBACKGROUNDS", (0, 0), (-1, -1), [colors.white, colors.HexColor("#f6f6f6")]),
            ]
        )
    )
    return table


def _section_flowables(section: DossierSection, styles, guidance_style) -> list:
    heading = f"{section.number}. {section.title}"
    flow: list = [Spacer(1, 4 * mm), Paragraph(heading, styles["Heading2"])]
    flow.append(Paragraph(section.guidance, guidance_style))
    if section.citations:
        rows = [["Reference", "Obligation", "Effective date"]]
        rows.extend([c.reference, c.title, c.effective_date.isoformat()] for c in section.citations)
        table = Table(rows, colWidths=[28 * mm, 110 * mm, 27 * mm])
        table.setStyle(
            TableStyle(
                [
                    ("FONTSIZE", (0, 0), (-1, -1), 8),
                    ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
                    ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#eaeaea")),
                    ("GRID", (0, 0), (-1, -1), 0.4, colors.HexColor("#cccccc")),
                    ("VALIGN", (0, 0), (-1, -1), "TOP"),
                ]
            )
        )
        flow.append(Spacer(1, 2 * mm))
        flow.append(table)
    return flow
