"""Record-keeping duties (Art. 12 and Art. 26(6)).

The two are separate duties on separate parties and they are routinely conflated.
Art. 12 obliges the **provider** to design automatic logging into the system.
Art. 26(6) obliges the **deployer** to keep the logs that system generates, for at
least six months unless other Union or national law says otherwise.

Attestor states the six-month floor and says it is a floor. It deliberately does
not compute a retention end date: the actual period depends on sectoral law the
engine does not model, and inventing a date would be the kind of confident wrong
answer this project exists to avoid.
"""

from attestor.classifier.model import Classification
from attestor.governance.model import LogRetentionDuty

# Art. 19(1) / Art. 26(6): "a period appropriate to the intended purpose ... of at
# least six months", unless provided otherwise by applicable Union or national law.
MINIMUM_RETENTION_MONTHS = 6

_LOG_OBLIGATIONS: dict[str, str] = {
    "art12_record_keeping": (
        "Provider duty: the system must technically allow the automatic recording of "
        "events (logs) over its lifetime. Six months is the retention floor the "
        "Regulation sets, not a target — sectoral law may require longer."
    ),
    "art26_6_log_retention": (
        "Deployer duty: keep the logs automatically generated by the system, to the "
        "extent they are under your control, for at least six months unless other "
        "applicable Union or national law provides otherwise."
    ),
}


def log_retention_duties(classification: Classification) -> tuple[LogRetentionDuty, ...]:
    """Return the record-keeping duties that apply, with their retention floor."""
    duties = [
        LogRetentionDuty(
            obligation_id=obligation.id,
            reference=obligation.reference,
            title=obligation.title,
            effective_date=obligation.effective_date,
            minimum_retention_months=MINIMUM_RETENTION_MONTHS,
            note=_LOG_OBLIGATIONS[obligation.id],
        )
        for obligation in classification.obligations
        if obligation.id in _LOG_OBLIGATIONS
    ]
    duties.sort(key=lambda d: d.obligation_id)
    return tuple(duties)
